// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace DBX.Native
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "dbx_csharp";





        /// <summary>
        ///  Open an in-memory database
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_open_in_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxHandle* dbx_open_in_memory();

        /// <summary>
        ///  Open a database at the given path
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxHandle* dbx_open(byte* path);

        /// <summary>
        ///  Load a database from a snapshot file
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_load_from_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxHandle* dbx_load_from_file(byte* path);

        /// <summary>
        ///  Insert a key-value pair into a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_insert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_insert(DbxHandle* handle, byte* table, byte* key, nuint key_len, byte* value, nuint value_len);

        /// <summary>
        ///  Get a value by key from a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_get(DbxHandle* handle, byte* table, byte* key, nuint key_len, byte** out_value, nuint* out_len);

        /// <summary>
        ///  Delete a key from a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_delete(DbxHandle* handle, byte* table, byte* key, nuint key_len);

        /// <summary>
        ///  Insert multiple key-value pairs at once (batch)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_insert_batch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_insert_batch(DbxHandle* handle, byte* table, byte** keys, nuint* key_lens, byte** values, nuint* value_lens, nuint count);

        /// <summary>
        ///  Scan all key-value pairs in a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_scan", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_scan(DbxHandle* handle, byte* table, DbxScanResult** out_result);

        /// <summary>
        ///  Scan a range of keys [start_key, end_key)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_range", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_range(DbxHandle* handle, byte* table, byte* start_key, nuint start_key_len, byte* end_key, nuint end_key_len, DbxScanResult** out_result);

        /// <summary>
        ///  Get the number of entries in a scan result
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_scan_result_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint dbx_scan_result_count(DbxScanResult* result);

        /// <summary>
        ///  Get a key from a scan result by index
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_scan_result_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_scan_result_key(DbxScanResult* result, nuint index, byte** out_key, nuint* out_key_len);

        /// <summary>
        ///  Get a value from a scan result by index
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_scan_result_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_scan_result_value(DbxScanResult* result, nuint index, byte** out_value, nuint* out_value_len);

        /// <summary>
        ///  Free a scan result
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_scan_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_scan_result_free(DbxScanResult* result);

        /// <summary>
        ///  Count rows in a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_count(DbxHandle* handle, byte* table, nuint* out_count);

        /// <summary>
        ///  Flush database to disk
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_flush", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_flush(DbxHandle* handle);

        /// <summary>
        ///  Get all table names
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_table_names", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_table_names(DbxHandle* handle, DbxStringList** out_list);

        /// <summary>
        ///  Get the number of strings in a string list
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_string_list_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint dbx_string_list_count(DbxStringList* list);

        /// <summary>
        ///  Get a string from a string list by index
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_string_list_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_string_list_get(DbxStringList* list, nuint index, byte** out_str, nuint* out_len);

        /// <summary>
        ///  Free a string list
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_string_list_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_string_list_free(DbxStringList* list);

        /// <summary>
        ///  Run garbage collection
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_gc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_gc(DbxHandle* handle, nuint* out_deleted);

        /// <summary>
        ///  Check if the database is encrypted. Returns 1 if encrypted, 0 if not.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_is_encrypted", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_is_encrypted(DbxHandle* handle);

        /// <summary>
        ///  Execute a SQL statement. Returns the number of affected/returned rows.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_execute_sql", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_execute_sql(DbxHandle* handle, byte* sql, nuint* out_affected);

        /// <summary>
        ///  Create an index on a table column
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_create_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_create_index(DbxHandle* handle, byte* table, byte* column);

        /// <summary>
        ///  Drop an index from a table column
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_drop_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_drop_index(DbxHandle* handle, byte* table, byte* column);

        /// <summary>
        ///  Check if an index exists. Returns 1 if exists, 0 if not.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_has_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_has_index(DbxHandle* handle, byte* table, byte* column);

        /// <summary>
        ///  Save the in-memory database to a file
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_save_to_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_save_to_file(DbxHandle* handle, byte* path);

        /// <summary>
        ///  Get the current MVCC timestamp
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_current_timestamp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong dbx_current_timestamp(DbxHandle* handle);

        /// <summary>
        ///  Allocate a new commit timestamp
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_allocate_commit_ts", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong dbx_allocate_commit_ts(DbxHandle* handle);

        /// <summary>
        ///  Insert a versioned key-value pair (MVCC)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_insert_versioned", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_insert_versioned(DbxHandle* handle, byte* table, byte* key, nuint key_len, byte* value, nuint value_len, ulong commit_ts);

        /// <summary>
        ///  Read a specific version of a key (Snapshot Read)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_get_snapshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_get_snapshot(DbxHandle* handle, byte* table, byte* key, nuint key_len, ulong read_ts, byte** out_value, nuint* out_len);

        /// <summary>
        ///  Free a value returned by dbx_get or dbx_get_snapshot
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_free_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_free_value(byte* value, nuint len);

        /// <summary>
        ///  Close a database
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_close(DbxHandle* handle);

        /// <summary>
        ///  Begin a transaction
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_begin_transaction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxTransaction* dbx_begin_transaction(DbxHandle* handle);

        /// <summary>
        ///  Insert a key-value pair in a transaction (buffered)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_insert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_insert(DbxTransaction* tx, byte* table, byte* key, nuint key_len, byte* value, nuint value_len);

        /// <summary>
        ///  Delete a key in a transaction (buffered)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_delete(DbxTransaction* tx, byte* table, byte* key, nuint key_len);

        /// <summary>
        ///  Commit a transaction
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_commit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_commit(DbxTransaction* tx);

        /// <summary>
        ///  Rollback a transaction
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_rollback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_transaction_rollback(DbxTransaction* tx);


    }


    /// <summary>
    ///  Opaque handle to a DBX database instance
    /// </summary>
    public enum DbxHandle
    {
    }

    /// <summary>
    ///  Opaque handle to a DBX transaction
    /// </summary>
    public enum DbxTransaction
    {
    }

    /// <summary>
    ///  Opaque handle to scan results
    /// </summary>
    public enum DbxScanResult
    {
    }

    /// <summary>
    ///  Opaque handle to string list
    /// </summary>
    public enum DbxStringList
    {
    }


}
