// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace DBX.Native
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "dbx_csharp";





        /// <summary>
        ///  Open an in-memory database
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_open_in_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxHandle* dbx_open_in_memory();

        /// <summary>
        ///  Open a database at the given path
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxHandle* dbx_open(byte* path);

        /// <summary>
        ///  Insert a key-value pair into a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_insert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_insert(DbxHandle* handle, byte* table, byte* key, nuint key_len, byte* value, nuint value_len);

        /// <summary>
        ///  Get a value by key from a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_get(DbxHandle* handle, byte* table, byte* key, nuint key_len, byte** out_value, nuint* out_len);

        /// <summary>
        ///  Delete a key from a table
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_delete(DbxHandle* handle, byte* table, byte* key, nuint key_len);

        /// <summary>
        ///  Begin a transaction
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_begin_transaction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DbxTransaction* dbx_begin_transaction(DbxHandle* handle);

        /// <summary>
        ///  Insert a key-value pair in a transaction (buffered)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_insert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_insert(DbxTransaction* tx, byte* table, byte* key, nuint key_len, byte* value, nuint value_len);

        /// <summary>
        ///  Delete a key in a transaction (buffered)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_delete(DbxTransaction* tx, byte* table, byte* key, nuint key_len);

        /// <summary>
        ///  Commit a transaction
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_transaction_commit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int dbx_transaction_commit(DbxTransaction* tx);

        /// <summary>
        ///  Free a value returned by dbx_get
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_free_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_free_value(byte* value, nuint len);

        /// <summary>
        ///  Close a database
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dbx_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dbx_close(DbxHandle* handle);


    }


    /// <summary>
    ///  Opaque handle to a DBX database instance
    /// </summary>
    public enum DbxHandle
    {
    }

    /// <summary>
    ///  Opaque handle to a DBX transaction
    /// </summary>
    public enum DbxTransaction
    {
    }


}
