/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Database handle */
export declare class Database {
  /** Open an in-memory database */
  static openInMemory(): Database
  /** Open a database at the given path */
  static open(path: string): Database
  /** Insert a key-value pair into a table */
  insert(table: string, key: Buffer, value: Buffer): void
  /** Get a value by key from a table */
  get(table: string, key: Buffer): Buffer | null
  /** Delete a key from a table */
  delete(table: string, key: Buffer): void
  /** Insert multiple key-value pairs at once (batch) */
  insertBatch(table: string, rows: Array<Array<Buffer>>): void
  /** Delete multiple keys at once (batch) */
  deleteBatch(table: string, keys: Array<Buffer>): void
  /** Scan all key-value pairs in a table */
  scan(table: string): Array<Array<Buffer>>
  /** Scan a range of keys in a table [start_key, end_key) */
  range(table: string, startKey: Buffer, endKey: Buffer): Array<Array<Buffer>>
  /** Count the number of rows in a table */
  count(table: string): number
  /** Flush the database to disk */
  flush(): void
  /** Get all table names */
  tableNames(): Array<string>
  /** Run garbage collection (MVCC version cleanup) */
  gc(): number
  /** Check if the database is encrypted */
  isEncrypted(): boolean
  /** Execute a SQL statement (SELECT/INSERT/UPDATE/DELETE) */
  executeSql(sql: string): number
  /** Drop a table */
  dropTable(tableName: string): void
  /** Check if a table exists */
  tableExists(tableName: string): boolean
  /** List all tables */
  listTables(): Array<string>
  /** Create an index on a table column */
  createIndex(table: string, column: string): void
  /** Drop an index from a table column */
  dropIndex(table: string, column: string): void
  /** Check if an index exists on a table column */
  hasIndex(table: string, column: string): boolean
  /** Save the in-memory database to a file */
  saveToFile(path: string): void
  /** Load a database from a file into memory */
  static loadFromFile(path: string): Database
  /** Get the current MVCC timestamp */
  currentTimestamp(): number
  /** Allocate a new commit timestamp */
  allocateCommitTs(): number
  /** Insert a versioned key-value pair (MVCC) */
  insertVersioned(table: string, key: Buffer, value: Buffer, commitTs: number): void
  /** Read a specific version of a key (Snapshot Read) */
  getSnapshot(table: string, key: Buffer, readTs: number): Buffer | null
  /** Begin a new transaction */
  beginTransaction(): Transaction
  /** Close the database */
  close(): void
  /** Zero-copy scan - returns ScanResult that owns the data */
  scanZeroCopy(table: string): ScanResult
  /** Batch get - get multiple keys at once (reduces FFI overhead) */
  getBatch(table: string, keys: Array<Buffer>): Array<Buffer | undefined | null>
}

/** Zero-copy scan result - Rust owns the data, JavaScript gets read-only access */
export declare class ScanResult {
  /** Get the raw data as a Buffer (zero-copy, read-only) */
  asBuffer(): Buffer
  /** Get the number of key-value pairs */
  count(): number
  /** Parse the data into key-value pairs (fallback, requires copy) */
  toPairs(): Array<Array<Buffer>>
}

/** Transaction handle */
export declare class Transaction {
  /** Insert a key-value pair (buffered) */
  insert(table: string, key: Buffer, value: Buffer): void
  /** Delete a key (buffered) */
  delete(table: string, key: Buffer): void
  /** Execute SQL statement (INSERT/UPDATE/DELETE) */
  execute(sql: string): number
  /** Commit the transaction (batch processing) */
  commit(): void
}
